apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: heeldocker/infra-app-example:latest
          ports:
            - containerPort: 8080
          env:
            - name: DOMAIN
              value: "http://example.com"
